### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by resonantworks** [eddie3/gogrepo#10]
Small bug as of commit 'ae50d09ac83625496c14f8be784d341aa0dca3aa' line 678:
`    if game_item.md5 in md5_info:`
should be
`    if game_item.md5 not in md5_info:`

Thanks for the work!

**Comment by eddie3** [comment]
Thanks for the report! Oops.. It actually should be 
`            if game_item.md5 is not None:`

Fixed with 2f55a82c8e0666a06608dfd59f47d987646e8c69
