### ISSUE TITLE
[suggestion] Slight change to download -id behaviour?

### ISSUE THREAD

**Issue by TrollDecker** [eddie3/gogrepo#15]
Something I've noticed is that, in its current form, if you specify an ID that doesn't exist (whee, typos), the script jumps straight to trying to download ALL the games in your manifest. I don't think that's ideal behaviour, because if a user is going to the trouble of using -id, then they're not exact wanting to download everything in the first place.

I think instead, if it can't find an ID, it should just end there, with a message to explain what happened.

**Comment by eddie3** [comment]
Thanks for the report, I'll look into it. That's definitely a bug.

**Comment by eddie3** [comment]
Should be good now. Thanks
