### ISSUE TITLE
locale issue

### ISSUE THREAD

**Issue by diomhaireachd** [eddie3/gogrepo#16]
I've found a locale issue on windows with python 3 a bit of an edge case.

Basically without specifying the encoding in python3 it seems to use system default which on windows depends on locale the issue will only show with titles containing characters that are not present in the current code page so say the registered trademark symbol and the Japanese code page. This causes an error on write.

I fixed this by stealing the code snippet from user2395922 here https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2 then added in `encoding='utf-8'` all over the place. Seems to work in both python 3 and 2.7 only difference with 2.7 is line endings become unix. If you want I can provide it as a pull request, have no idea what I'm doing otherwise I'd probably have done that. That said there is probably a better way of doing it.

Anyway thanks for the script.

**Comment by eddie3** [comment]
Hi, thanks for reporting. I think this should be fixed now. Can you let me know if you still see the issue?  Thanks!

**Comment by diomhaireachd** [comment]
Sorry for the delay getting back to you. Yup everything seems fine now, thanks.
