### ISSUE TITLE
reCaptcha Problems

### ISSUE THREAD

**Issue by CriticalComposer** [eddie3/gogrepo#17]
I have attempted to login with this script on numerous occasions and I always get the "cannot continue, gog is asking for a reCAPTCHA :(  try again in a few minutes." issue. I have tried across multiple days even to no avail. I have even tried on the website and I am greeted with the reCAPTCHA aspect of the login every time. Does that mean that this script won't work anymore since GOG always requires the reCAPTCHA? Also, assuming that I can ever log in, how does the script handle 2 Factor Authentication?

**Comment by eddie3** [comment]
Yeah GOG just started to enforce reCAPTCHA all the time now. If you already have a "gog-cookies.dat" file from a previous login, it should still work. I think this could be solved by exporting your gog login cookie from your browser into a gog-cookies.dat file. need to look into it

**Comment by CriticalComposer** [comment]
Alright. I thought about grabbing my browser cookies but I didn't know what format your .dat was so I figured that wouldn't be much help. I don't mind trying to build the cookie.dat from my browser cookies but I would need to know the .dat formatting, if you don't mind passing that info out.

**Comment by eddie3** [comment]
I just pushed a gogrepo.py update to help import the cookies.

I was able to login to gog.com using Chrome, and export the cookies

1) Log into gog.com through your browser (and do the reCAPTCHA manually) 
2) Extract your cookies out of your browser (I used a Chrome extension called "cookies.txt"). 
3) Save the cookies as "gog-cookies.dat" and put it in the same directory as the gogrepo.py script itself 

If your gog-cookies.dat is valid, you can go straight to doing your 'update' and 'download' as normal.

**Comment by crsleeth** [comment]
Hi, thanks for work on this project. I'm having the same issue even after following your steps in the last reply.
