### ISSUE TITLE
impossible to download multiple languages

### ISSUE THREAD

**Issue by tesrtasr** [eddie3/gogrepo#2]
What I did:
- gogrepo.py update -os win linux -lang en de
- gogrepo.py download [targetdir]

Works nearly perfect, the windows and linux binaries are downloaded, but gogrepo seems to ignore the second language argument. The german version of the binary is never downloaded, not for win or linux.
Thanks for working on this helped me big times. My external drive died and everything downloading again manually ... probably wouldn't have even started...

**Comment by eddie3** [comment]
Thanks for reporting. I'll look into this in next few days.
