### ISSUE TITLE
[enhancement] Non-Galaxy installers

### ISSUE THREAD

**Issue by mnadareski** [eddie3/gogrepo#30]
Somewhat recently, there now exist 2 versions of the installers: one that includes GOG Galaxy bundled, and one without. The current downloader takes the default one, which includes Galaxy. It would be nice to either include the option to ALSO download the non-Galaxy ones or have it be an either-or.

**Comment by 07416** [comment]
What is the current behavior?

**Comment by mnadareski** [comment]
Assuming nothing changed, it downloads only the bundled installer.

**Comment by IdamkinI** [comment]
I that still relevant?
It seems that now only one version of offline installers is available for download, and all of them a doesn't include Galaxy

**Comment by eddie3** [comment]
I think GOG dropped this concept? If not please let me know.

**Comment by mnadareski** [comment]
Correct, it looks like this was dropped in the past couple years.
