### ISSUE TITLE
File naming inconsistency in comparison to Galaxy downloads.

### ISSUE THREAD

**Issue by m-lohmann** [eddie3/gogrepo#35]
I noticed that gogrepo consistently shows a file naming inconsistency, compared to downloads using the Galaxy downloader.

For example, if I download a file with Galaxy, named

`setup_cryptark_1.2_(15131).exe`

and then fire up gorgrepo to check for updates and download them, it does not recognize the already downloaded file and downloads it again as

`setup_cryptark_1.2_%2815131%29.exe`

The first time I didn’t think much about it and batch renamed all files to their proper form.

But when I ran the next update via gogrepo it wanted to download 64 GB of updates, and 90% of these already exist on my HDD, but aren’t detected because they are named properly.

For some reason gogrepo replaces open and closed parentheses with the ASCII representation of their hex values, `%28` instead of `(` and `%29` instead of `)`, respectively.

The result of this can be seen in this [screenshot](https://i.imgur.com/8Lu0ns7.png).

**Comment by JayB33** [comment]
There's already an open issue titled "Parentheses in filenames are not decoded " where the patch is also listed, but you have to edit the script manually. It seems this project is no longer maintained. There is also an undocumented feature, "clean" which you can call in the script (with "cleandir" and "-dryrun" options) which is the only easy way I can see to remove outdated files. "verify -delete" doesn't seem to actually clean the whole directory out for me.

**Comment by m-lohmann** [comment]
I already had manually added the changes without any success. Only after I did a full `gogrepo.py update` everything worked perfectly fine again.
