### ISSUE TITLE
Eador Master of the Broken World fails to fetch game files

### ISSUE THREAD

**Issue by disi** [eddie3/gogrepo#5]
There was an update on the game today and I tried to fetch the new installer and dlc. On the Account website I can see the links as:
<pre>https://www.gog.com/downlink/eador_masters_of_the_broken_world/en1installer4
https://www.gog.com/downlink/eador_masters_of_the_broken_world/en1patch2
https://www.gog.com/downlink/eador_masters_of_the_broken_world/de1installer4
https://www.gog.com/downlink/eador_masters_of_the_broken_world/de1patch2</pre>
it does fetch the extras just fine.

<pre>  'downloads': [],
  'extras': [{'desc': u'Handbuch',
              'href': u'https://www.gog.com/downlink/file/eador_masters_of_the_broken_world/21653',</pre>

Actual only the patch version increased and I've got the installer from a previous download.
http://i.imgur.com/2JL82SH.jpg

**Comment by disi** [comment]
I think they changed the api for game downloads... I ran a complete update and no game files at all.

**Comment by disi** [comment]
This never triggers in filter_downloads(out_list, downloads_dict, lang_list, os_list):
<pre>    for lang in downloads_dict:
        if lang in valid_langs:
            info('valid lang')</pre>

**Comment by disi** [comment]
It appears, they do not return a dict any more for item_json_data['downloads'], but a list. This seems to work:
<pre>                # prase json data for downloads/extras/dlcs
                filter_downloads(item.downloads, dict(item_json_data['downloads']), lang_list, os_list)
                filter_extras(item.extras, item_json_data['extras'])
                filter_dlcs(item, item_json_data['dlcs'], lang_list, os_list)</pre>

**Comment by eddie3** [comment]
Seems you're right.. and converting the list to dict seems to go pretty smoothly.
Do you know off hand if item_json_data['dlcs'] is also affected? We may have to do the same trick there (or fix the filter functions to accept GOG's new list format)

**Comment by eddie3** [comment]
Fixed. I did the dict() conversion right in filter_downloads to ensure that calls from filter_dlc() aren't missed.
