### ISSUE TITLE
Unable to Verify games with Windows directory specified

### ISSUE THREAD

**Issue by seattleandrew** [eddie3/gogrepo#51]
I have been successfully downloading my GOG collection to a remote (SMB fileshare) directory from Windows 10, however when I attempt to verify the games and I specify any directory, I receive the error below.

The code I use to initiate the verification is the following batch script
`@ECHO ON
gogrepo.py verify 
\\NAS\FamilyStorage\Family\Games\GOG`

`SyntaxError: invalid syntax
16:21:30 | loading local manifest...
16:21:31 | fatal...
Traceback (most recent call last):
  File "C:\gogrepo\gogrepo.py", line 2362, in <module>
    main(process_argv(sys.argv))
  File "C:\gogrepo\gogrepo.py", line 2335, in main
    cmd_verify(args.gamedir, args.skipextras,args.skipids,check_md5, check_filesize, check_zips, args.delete, args.clean,args.ids,  args.os, args.lang,args.skipgalaxy,args.skipstandalone,args.skipshared, args.forceverify)
  File "C:\gogrepo\gogrepo.py", line 1985, in cmd_verify
    items = load_manifest()
  File "C:\gogrepo\gogrepo.py", line 337, in load_manifest
    return eval(ad)
  File "<string>", line 31896
    u'downloads':
                 ^
SyntaxError: invalid syntax`

**Comment by Shiryou** [comment]
It looks like there's an issue on line 31896 of your `gog-manifest.dat` file. Can you check if there's anything unusual on that line?

On a side note: I've noticed that running this over the network can be very slow. If your NAS supports Python (which some do), it might be quicker to SSH into the NAS and run `verify` locally.

**Comment by eddie3** [comment]
Please re-open if this is still an issue.  Thanks.
