### ISSUE TITLE
update with different or additional languages than en (English)

### ISSUE THREAD

**Issue by disi** [eddie3/gogrepo#6]
Some games like Randal's Monday and a lot more have all languages build into one file.
If you choose more than one languages (i.e. -lang en de), the script will iterate through the languages and add the file twice to the manifest.
This results in two downloads for the same file, for the second it actual counts into negative for displaying progress.

If you choose only a different languages than en (English), it will not add files for games that doesn't support the language. For example '-lang de' will not fetch any game files for 'Memoria'.

**Comment by disi** [comment]
Maybe this works (paragraph 3)
https://github.com/disi/gogrepo/wiki

**Comment by disi** [comment]
They are not really duplicate url but the same file, like this:
<pre> 'downloads': [{'desc': u'Broken Age: The Complete Adventure',
                 'href': u'https://www.gog.com/downlink/broken_age/de1installer2',
                 'lang': u'Deutsch',
                 'md5': 'f9cfbe7fb3dc460a435ba6e91d8e5a48',
                 'name': 'setup_broken_age_2.2.0.8.exe',
                 'os_type': u'windows',
                 'size': 2144565808,
                 'version': u'2.0 (gog-8)'},
                {'desc': u'Patch 2.2',
                 'href': u'https://www.gog.com/downlink/broken_age/de1patch1',
                 'lang': u'Deutsch',
                 'md5': '0e538e59b33909210b0caed3c3868dd8',
                 'name': 'patch_broken_age_2.2.1.9.exe',
                 'os_type': u'windows',
                 'size': 1794432,
                 'version': u'2.0 (gog-8) -> 2.2 (gog-9)'},
                {'desc': u'Broken Age: The Complete Adventure',
                 'href': u'https://www.gog.com/downlink/broken_age/en1installer2',
                 'lang': u'English',
                 'md5': 'f9cfbe7fb3dc460a435ba6e91d8e5a48',
                 'name': 'setup_broken_age_2.2.0.8.exe',
                 'os_type': u'windows',
                 'size': 2144565808,
                 'version': u'2.0 (gog-8)'},
                {'desc': u'Patch 2.2',
                 'href': u'https://www.gog.com/downlink/broken_age/en1patch1',
                 'lang': u'English',
                 'md5': '0e538e59b33909210b0caed3c3868dd8',
                 'name': 'patch_broken_age_2.2.1.9.exe',
                 'os_type': u'windows',
                 'size': 1794432,
                 'version': u'2.0 (gog-8) -> 2.2 (gog-9)'}],</pre>

**Comment by eddie3** [comment]
yeah the href will be different, but the file name and MD5 should be the same, as you show above. this is only known after doing the href fetch itself. Some commands like download/verify/backup/import will need to take this into consideration.

I'm starting to wonder if using AttrDict is getting out of hand.. thinking of maybe going SQLite route in future.

Hope to have some time this weekend for this.

**Comment by disi** [comment]
If we assume that the file name is unique for all games?

Extras have wc4_wallpapers.zip for example.
DLC have setup_starpoint_gemini_2_secrets_of_aethera_2.2.0.8.exe
Game files have setup_sw_rebellion_2.0.0.4.exe or setup_sw_rebellion_german_2.0.0.4.exe

I added all downloads to a dict with key dest_file before adding the dict to the queue, this seems to work just fine
https://github.com/disi/gogrepo/commit/f7c9d599977345e9eae2ecf80da99b261f7ed7c6

**Comment by eddie3** [comment]
Thank you disi! Looks good tome.. I have merged your changes.
